version: '3'
services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: web1
    ports:
      - '5000:5000'

  web2:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: web2
    ports:
      - '5001:5000'
